name: 'Changelog Creator'
description: 'A GitHub action built using Kotlin/JS that creates your release notes/changelog using the PRs closed in a milestone.'
author: 'Mohitesh Aeron'
branding:
  icon: 'award'
  color: 'green'
inputs:
  configuration:
    required: false
    description: 'Defines the relative path to the configuration file.'
  milestone:
    required: false
    description: 'Defines the milestone for which change log needs to be generated. If not supplied last closed milestone will be used'
  failOnError:
    description: 'Defines if the action should result in a build failure, if an error was discovered'
    required: false
    default: "false"
  owner:
    description: 'Definer the owner of the repo, uses `env.GITHUB_REPOSITORY` to resolve owner name by default'
    required: false
  repo:
    description: 'Definer the name of the repo, uses `env.GITHUB_REPOSITORY` to resolve repo name by default'
    required: false
  token:
    required: false
    description: 'Defines the token to use to execute the git API requests with, uses `env.GITHUB_TOKEN` by default'
outputs:
  changelog:
    description: 'The built release changelog built from the merged pull requests'
  owner:
    description: 'Specifies the owner of the repository processed'
  repo:
    description: 'Describes the repository name, which was processed'
  milestone:
    description: 'Milestone either provided in the input or resolved from the last closed list'
  failed:
    description: 'Defines if there was an issue with the action run, and the changelog may not have been generated correctly. [true, false]'
runs:
  using: 'node12'
  main: 'dist/index.js'