name: 'Changelog Creator'
description: 'A GitHub action built using Kotlin/JS that creates your release notes/changelog using the PRs closed in a milestone. Heavily taken from mikepenz/release-changelog-generator'
author: 'Mohitesh Aeron'
branding:
  icon: 'award'
  color: 'green'
inputs:
  configuration:
    required: false
    description: 'Defines the relative path to the configuration file.'
  owner:
    required: false
    description: 'Defines the owner of the repository to create the changelog for'
  repo:
    required: false
    description: 'Defines the repository to create the changelog for'
  milestone:
    required: false
    description: 'Defines the milestone for which change log needs to be generated'
  failOnError:
    description: 'Defines if the action should result in a build failure, if an error was discovered'
    required: false
    default: "false"
  outputFile:
    required: false
    description: 'If defined, the changelog will get written to this file. (relative to the checkout dir)'
  token:
    required: false
    description: 'Defines the token to use to execute the git API requests with, uses `env.GITHUB_TOKEN` by default'
outputs:
  changelog:
    description: 'The built release changelog built from the merged pull requests'
  owner:
    description: 'Specifies the owner of the repository processed'
  repo:
    description: 'Describes the repository name, which was processed'
  failed:
    description: 'Defines if there was an issue with the action run, and the changelog may not have been generated correctly. [true, false]'
runs:
  using: 'node12'
  main: 'distributions/action-entry-point.js'